apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: color-app-replicaset
  labels:
    app: color-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: color-app
  template:
    metadata:
      labels:
        app: color-app
    spec:
      containers:
      - name: webapp
        image: nortontube/color-app:27b8279e1e2191382e130cbdf7929ef90533ca20
        imagePullPolicy: Never
        ports:
        - containerPort: 80
         
        # 1. The Cable (Inside the container)
        volumeMounts:
        - name: app-storage
          mountPath: /data

      # 2. The Hardware (At the Pod level)
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: color-app-pvc
